-- GENERATED BY SCRIPT: DO NOT EDIT
--  this is where editor loads and saves level. Copy and paste from here to normal game



function initLevels()
	levels = {}
levels[1] = {isTutorial = true, initialStructures = {}, initialPeasantPopulation = 0, id = 1, mapBlueprint = {townHallLoc = {y = 2, x = 2}, defaultTerrainType = "plains", roads = {}, height = 4, terrain = {}, width = 4}, spawnPoints = {}, initialResources = {stone = 0, timber = 0, gold = 100}, initialWallType = "stonewall", wallGapOrientation = 0, name = "foo", initialTowers = {}, restrictions = {villageStructs = {}, structures = {}, towers = {}, villageTowers = {}, upgrades = {}}, initialVillageStructures = {}, description = "desc", waves = {}}
end

-- ====================================================
